### ISSUE TITLE
clean正则的优化(为什么这里的代码突然不用var声明变量了，污染全局!)

### ISSUE THREAD

**Issue by deepred5** [msongz/importEDL#1]
``` javascript
function clean(text) {
    var reg = /(^\s*)|(\s*$)|(\")/g;
    return text.replace(reg, "");
}
```

**Comment by msongz** [comment]
var 应该是忘记了加！言归正传，这个优化的正则貌似不太正确，你尝试用这个样本做测试（ "ab cd ef"）不包括括号，注意第一个空格，过滤出期待的（ab cd ef）。

**Comment by deepred5** [comment]
的确没想到
var reg = /(^\s+)|(\s+$)|(\")/g;
应该可以

**Comment by msongz** [comment]
可以了！开心啊！

**Comment by msongz** [comment]
发现没有+号也可以
var reg = /(^\s)|(\s$)|(\")/g;

**Comment by deepred5** [comment]
如果开始或结尾有多个空格，+（匹配1或多个）可以全部去除，就是trim()函数的原理而已。

**Comment by msongz** [comment]
根据目前的edl文件来看，每个参数前都会有一个空格，结尾不带空格，中间有可能有引号和空格，就是样本那个样子。trim没接触过，受教了！

**Comment by deepred5** [comment]
平时也用AE和vegas，所以你的脚本还是比较不错的
